const $=s=>document.querySelector(s);
const chapters=[
{title:"Welcome to Your Universe ✨",desc:"A small digital universe for the biggest place in my heart.",render:()=>`<div class="content-center"><div class="big-number">∞</div><div class="note"><strong>Jaanu,</strong><br>Today the whole universe has one important event: YOU. Every star, every sparkle and every little surprise here is a reminder that you are deeply special. Ready to unlock your birthday magic?</div></div>`},
{title:"The Birthday Countdown ⏳",desc:"A dramatic little countdown before your special reveal.",render:()=>`<div class="content-center"><div id="countNum" class="big-number">3</div><p id="countText">Get ready, birthday queen...</p><button class="primary-btn" id="runCountdown">Start Countdown</button></div>`},
{title:"Your Birthday Soundtrack 🎵",desc:"Press play and let the atmosphere begin.",render:()=>`<div class="content-center"><div class="big-number">♫</div><p class="note">Your song is waiting in <strong>birthday.mp3</strong>. Tap the music button above or use the player below.</p><audio controls loop src="birthday.mp3" style="width:100%;max-width:450px"></audio></div>`},
{title:"A Letter From My Heart 💌",desc:"Not just words—little pieces of feeling.",render:()=>`<div class="note" id="typingNote"></div>`},
{title:"100 Reasons to Smile 🌷",desc:"Tap each card to reveal a compliment.",render:()=>`<div class="cards">${["Your eyes","Your smile","Your kindness","Your patience","Your hair","Your voice","Your honesty","Your courage","Your little habits","Your beautiful heart"].map((x,i)=>`<button class="mini-card compliment" data-i="${i}">💙<br>${x}<small>Tap to reveal</small></button>`).join("")}</div>`},
{title:"Our Memory Scrapbook 📸",desc:"Put your own photos inside the photos folder.",render:()=>`<div class="photo-grid">${Array.from({length:10},(_,i)=>`<figure style="--r:${i%2?2:-2}deg"><img src="./photos/rm${i+1}.jpg" alt="Memory ${i+1}" loading="lazy" onerror="this.onerror=null;this.src='./photos/placeholder.svg';"><figcaption>Memory ${i+1} ♡</figcaption></figure>`).join("")}</div>`},
{title:"Make a Birthday Wish 🎂",desc:"Tap the cake to blow out the candles.",render:()=>`<div class="content-center"><div class="cake" id="cake">🎂</div><p id="cakeText">Tap the cake and make your wish.</p></div>`},
{title:"A Little Shayari 🌙",desc:"For the person who makes ordinary days feel poetic.",render:()=>`<div class="note">Teri muskurahat se roshan meri har shaam rahe,<br>tere chehre par hamesha khushiyon ka naam rahe.<br>Janamdin par bas itni si dua hai meri,<br>tu jahan bhi rahe, khushiyon ka paighaam rahe. 💙</div>`},
{title:"Mystery Gift Boxes 🎁",desc:"Only one rule: open every box.",render:()=>`<div class="gift-row">${["🎁","🎀","💝"].map((x,i)=>`<button class="gift" data-gift="${i}">${x}</button>`).join("")}</div><p class="content-center" id="giftText">Choose a gift...</p>`},
{title:"Love Meter ∞%",desc:"This meter has no maximum.",render:()=>`<div class="content-center"><div class="big-number">∞%</div><div class="meter"><div></div></div><p class="note">Love level: permanently overloaded. No reset button available. 💙</p></div>`},
{title:"Choose a Star Wish ⭐",desc:"Pick a star and receive a wish.",render:()=>`<div class="stars">${["★","★","★","★","★"].map((x,i)=>`<button class="star" data-star="${i}">${x}</button>`).join("")}</div><p class="note content-center" id="starText">Your wish is hiding inside a star.</p>`},
{title:"Magic Mirror 🪞",desc:"A reminder of what makes you beautiful.",render:()=>`<div class="content-center"><div class="big-number">♡</div><div class="note"><strong>Mirror message:</strong><br>You are not only beautiful in pictures. Your real magic is in the way you care, laugh, try, forgive and make someone feel at home.</div></div>`},
{title:"Fortune Wheel of Love 🔮",desc:"Tap to receive your birthday fortune.",render:()=>`<div class="content-center"><div class="big-number">☼</div><button class="primary-btn" id="fortuneBtn">Reveal Fortune</button><p class="note" id="fortuneText">Your fortune is waiting...</p></div>`},
{title:"A Funny Surprise 🎬",desc:"Add your funny birthday video as happy.mp4.",render:()=>`<div class="video-box"><video controls playsinline preload="metadata"><source src="./happy.mp4" type="video/mp4">Your browser does not support MP4 video.</video></div><p class="note">If the video does not appear, check that the filename is exactly <strong>happy.mp4</strong>.</p>`},
{title:"Our Future Dreams 🌌",desc:"A tiny timeline of beautiful possibilities.",render:()=>`<div class="timeline"><article><h4>Today</h4><p>More smiles, more memories and a birthday full of warmth.</p></article><article><h4>One Day</h4><p>More places to explore, more photos to collect and more stories to tell.</p></article><article><h4>Always</h4><p>Keep choosing kindness, laughter and each other through every season.</p></article></div>`},
{title:"The Wish Tree 🌳",desc:"Plant a wish and watch the tree grow.",render:()=>`<div class="content-center"><div class="big-number" id="tree">🌱</div><button class="primary-btn" id="plantBtn">Plant a Wish</button><p class="note" id="treeText">One small wish can grow into a beautiful future.</p></div>`},
{title:"Love & Kiss Rain 💋",desc:"Activate a 10-second celebration.",render:()=>`<div class="content-center"><div class="big-number">💙</div><button class="primary-btn" id="rainBtn">Start Love Rain</button><p class="note" id="rainText">Hearts and kisses are ready to fall.</p></div>`},
{title:"The Secret Door 🔐",desc:"A private little gate for your special nickname.",render:()=>`<div class="content-center secret"><div class="big-number">🔐</div><p>Hint: our secret word is the one you already know.</p><input id="secretInput" type="password" placeholder="Enter secret word"><br><button class="primary-btn" id="secretBtn">Unlock</button><p id="secretText"></p></div>`},
{title:"Your Birthday Certificate 🏆",desc:"Officially certified as one-of-one.",render:()=>`<div class="note content-center"><div style="font-size:3rem">🏆</div><h3>Certificate of Infinite Specialness</h3><p>This certifies that <strong>Jaanu</strong> is officially loved, celebrated and appreciated beyond measurable limits.</p><p>Issued with endless affection 💙</p></div>`},
{title:"The Grand Final Reveal 💙",desc:"The last chapter is not an ending.",render:()=>`<div class="content-center"><div class="big-number">💙</div><div class="note"><strong>Happy Birthday, meri Jaanu!</strong><br><br>May your days be softer, your dreams bigger, your smile brighter and your heart lighter. Whatever life brings, I hope you always remember that you deserve genuine happiness, respect, peace and beautiful surprises.<br><br>Keep shining. Keep smiling. Keep being you. 🌷✨<br><br><strong>Forever sending you love, hugs and countless birthday wishes.</strong></div></div>`}
];
let index=0, soundOn=true;
const loveNotes=["Tumhari smile meri favourite notification hai. 💙","Aaj ka reminder: you are precious, not replaceable.","Tumhare liye happiness ka unlimited data pack activate hai.","Agar kindness ek art hai, tum masterpiece ho.","Tumhari presence ordinary moments ko special bana deti hai."];
function openModal(content){$("#modalContent").innerHTML=content;$("#modal").classList.remove("hidden")}
function closeModal(){$("#modal").classList.add("hidden")}
function update(){const c=chapters[index];$("#chapterEyebrow").textContent=`CHAPTER ${String(index+1).padStart(2,"0")}`;$("#chapterTitle").textContent=c.title;$("#chapterDescription").textContent=c.desc;$("#chapterContent").innerHTML=c.render();$("#progressText").textContent=`Chapter ${index+1} of ${chapters.length}`;$("#progressPercent").textContent=Math.round((index+1)/chapters.length*100)+"%";$("#progressBar").style.width=((index+1)/chapters.length*100)+"%";$("#backBtn").disabled=index===0;$("#nextBtn").textContent=index===chapters.length-1?"Replay Universe ↺":"Continue →";localStorage.setItem("birthdayChapter",index);bindChapter()}
function bindChapter(){
$("#runCountdown")?.addEventListener("click",()=>{let n=3;const el=$("#countNum"),tx=$("#countText");el.textContent=n;const t=setInterval(()=>{n--;if(n>0)el.textContent=n;else{clearInterval(t);el.textContent="HAPPY BIRTHDAY 💙";tx.textContent="The universe is celebrating you!";confetti() }},900)});
$("#cake")?.addEventListener("click",()=>{$("#cake").textContent="🍰";$("#cakeText").textContent="Wish made! Candles blown! ✨";confetti()});
document.querySelectorAll(".compliment").forEach(b=>b.addEventListener("click",()=>{const arr=["Your eyes carry warmth.","Your smile can soften a hard day.","Your kindness is quietly powerful.","Your patience deserves appreciation.","Your hair is part of your signature charm.","Your voice feels familiar and comforting.","Your honesty makes trust feel safe.","Your courage is stronger than you think.","Your little habits make you uniquely you.","Your heart deserves gentle treatment."];openModal(`<h2>${arr[b.dataset.i]}</h2><p>One more reason to smile today. 💙</p>`) }));
document.querySelectorAll("[data-gift]").forEach(b=>b.addEventListener("click",()=>{$("#giftText").textContent=["Gift 1: unlimited hugs 🤗","Gift 2: a lifetime of tiny surprises 🎀","Gift 3: peace, laughter and love 💝"][b.dataset.gift];confetti()}));
document.querySelectorAll("[data-star]").forEach(b=>b.addEventListener("click",()=>$("#starText").textContent=["May your biggest dream find its way to you.","May your smile stay brighter than every star.","May peace find you in every busy season.","May your efforts turn into beautiful results.","May you always feel loved and respected."][b.dataset.star]));
$("#fortuneBtn")?.addEventListener("click",()=>$("#fortuneText").textContent=["A year of brave beginnings is opening.","A beautiful surprise is closer than you think.","Your kindness will return in unexpected ways.","Your next chapter deserves your full confidence."][Math.floor(Math.random()*4)]);
$("#plantBtn")?.addEventListener("click",()=>{$("#tree").textContent=["🌱","🌿","🌳","🌳🌸"][Math.min((Number(localStorage.getItem("wishGrowth")||0)+1),3)];localStorage.setItem("wishGrowth",Math.min(Number(localStorage.getItem("wishGrowth")||0)+1,3));$("#treeText").textContent="Wish planted. Keep watering it with hope. ✨"});
$("#rainBtn")?.addEventListener("click",()=>{let s=10;$("#rainText").textContent="💙 💋 💙 💋 💙";const t=setInterval(()=>{document.body.insertAdjacentHTML("beforeend",`<span class="falling" style="left:${Math.random()*100}%;animation-duration:${2+Math.random()*3}s">💙</span>`);s--;if(!s)clearInterval(t)},300)});
$("#secretBtn")?.addEventListener("click",()=>{$("#secretText").textContent=$("#secretInput").value.toLowerCase()==="kuchupuchu"?"Unlocked! You are my favourite secret. 💙":"Try again, jaanu 😉"});
}
function go(n){index=Math.max(0,Math.min(chapters.length-1,n));update();window.scrollTo({top:0,behavior:"smooth"})}
function confetti(){for(let i=0;i<45;i++){const s=document.createElement("span");s.className="falling";s.textContent=["💙","💋","✨","🎉"][Math.floor(Math.random()*4)];s.style.left=Math.random()*100+"%";s.style.animationDuration=2+Math.random()*3+"s";document.body.appendChild(s);setTimeout(()=>s.remove(),5000)}}
$("#startBtn").addEventListener("click",()=>{go(0);$("#bgMusic").play().catch(()=>{});confetti()});
$("#surpriseBtn").addEventListener("click",()=>openModal(`<h2>Random Love Note 💌</h2><p>${loveNotes[Math.floor(Math.random()*loveNotes.length)]}</p>`));
$("#nextBtn").addEventListener("click",()=>go(index===chapters.length-1?0:index+1));$("#backBtn").addEventListener("click",()=>go(index-1));$("#modalClose").addEventListener("click",closeModal);$("#modal").addEventListener("click",e=>{if(e.target.id==="modal")closeModal()});
$("#themeToggle").addEventListener("click",()=>document.body.classList.toggle("light"));
$("#soundToggle").addEventListener("click",()=>{soundOn=!soundOn;$("#bgMusic").muted=!soundOn;$("#soundToggle").textContent=soundOn?"🔊":"🔇";if(soundOn)$("#bgMusic").play().catch(()=>{})});
$("#resetBtn").addEventListener("click",()=>{localStorage.removeItem("birthdayChapter");localStorage.removeItem("wishGrowth");go(0)});
document.querySelectorAll("[data-jump]").forEach(b=>b.addEventListener("click",()=>go(Number(b.dataset.jump))));
const saved=Number(localStorage.getItem("birthdayChapter")||0);index=saved;update();
const canvas=$("#particleCanvas"),ctx=canvas.getContext("2d");let dots=[];function resize(){canvas.width=innerWidth;canvas.height=innerHeight;dots=Array.from({length:Math.min(100,Math.floor(innerWidth/10))},()=>({x:Math.random()*canvas.width,y:Math.random()*canvas.height,r:Math.random()*2+0.5,v:Math.random()*.4+.1}))}function animate(){ctx.clearRect(0,0,canvas.width,canvas.height);ctx.fillStyle="rgba(255,255,255,.5)";dots.forEach(d=>{d.y-=d.v;if(d.y<0)d.y=canvas.height;ctx.beginPath();ctx.arc(d.x,d.y,d.r,0,Math.PI*2);ctx.fill()});requestAnimationFrame(animate)}addEventListener("resize",resize);resize();animate();
const style=document.createElement("style");style.textContent=".falling{position:fixed;top:-40px;z-index:30;pointer-events:none;font-size:24px;animation:fall 4s linear forwards}@keyframes fall{to{transform:translateY(110vh) rotate(360deg);opacity:0}}";document.head.appendChild(style);
